[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "autogen>=0.9.9",
    "crewai>=0.186.1",
    "langchain>=0.3.27",
    "openai>=1.107.1",
]
